pipeline {
    agent {
        docker {
            image 'node:6-alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
   
    stages {
        stage('Checkout') {
    steps {
                script {
                     withCredentials([gitUsernamePassword(credentialsId: '6bff6f7a-4a95-4221-a05a-c07d07680c51', gitToolName: 'Default')]) {
                    sh 'git fetch --all'
                    }
                }
        
            }
          }
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
